//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComercioWeb
{
    public partial class Categorias
    {
        protected global::System.Web.UI.WebControls.GridView gvCategorias;
        protected global::System.Web.UI.WebControls.Button btnNuevaCategoria;
    }
}
