//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComercioWeb
{


    public partial class DetalleCompra
    {

        /// <summary>
        /// lblMensaje control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMensaje;

        /// <summary>
        /// lblNumeroCompra control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNumeroCompra;

        /// <summary>
        /// lblFecha control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblFecha;

        /// <summary>
        /// lblProveedor control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblProveedor;

        /// <summary>
        /// lblTotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotal;

        /// <summary>
        /// gvDetalles control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvDetalles;
    }
}
